# Generated by Django 2.2.4 on 2019-11-03 08:29

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import fund.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FbFunding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=255)),
                ('fund_name', models.CharField(max_length=255)),
                ('web_link', models.CharField(max_length=255, null=True)),
                ('opening_date', models.DateField()),
                ('closing_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurence', models.CharField(max_length=255)),
                ('occurence_no', models.PositiveIntegerField(null=True)),
                ('qualifiers', models.TextField(null=True)),
                ('key_contacts', models.TextField(null=True)),
                ('requirements', models.TextField(null=True)),
                ('file', models.FileField(null=True, upload_to=fund.models.doc_upload_path)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_funds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
