# Generated by Django 2.2.4 on 2019-11-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_fbfunding_document_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbfunding',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
