# Generated by Django 2.2.4 on 2019-11-03 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0003_fbfunding_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fbfunding',
            old_name='occurence',
            new_name='occurrence',
        ),
        migrations.RenameField(
            model_name='fbfunding',
            old_name='occurence_no',
            new_name='occurrence_no',
        ),
    ]
