# Generated by Django 2.2.4 on 2019-11-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0004_auto_20191103_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbfunding',
            name='document_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
