# Generated by Django 2.2.4 on 2019-11-03 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0005_auto_20191103_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbfunding',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_funds', to=settings.AUTH_USER_MODEL),
        ),
    ]
