# Generated by Django 2.2.4 on 2019-11-03 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_application', to=settings.AUTH_USER_MODEL)),
                ('funding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_applications', to='fund.FbFunding')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_applications', to='projects.FbProjects')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_approve_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
