# Generated by Django 2.2.4 on 2019-11-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbapplication',
            name='status',
            field=models.CharField(default='Not Submitted', max_length=255),
        ),
    ]
