# Generated by Django 2.2.4 on 2019-11-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_fbapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbapplication',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fbapplication',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
