# Generated by Django 2.2.4 on 2019-11-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20191111_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbapplication',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fbapplication',
            name='status',
            field=models.CharField(default='Not Submitted', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fbapplication',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
