# Generated by Django 2.2.4 on 2019-11-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20191111_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbapplication',
            name='status',
            field=models.CharField(choices=[('not submitted', 'Not Submitted')], default='not submitted', max_length=255, null=True),
        ),
    ]
