# Generated by Django 2.2.4 on 2019-11-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbprojects',
            name='budget',
            field=models.FloatField(null=True),
        ),
    ]
