# Generated by Django 2.2.4 on 2019-11-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_fbprojects_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fbprojects',
            name='categories',
        ),
    ]
