# Generated by Django 2.2.4 on 2019-11-11 02:33

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20191103_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbmilestones',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.doc_upload_path),
        ),
        migrations.AlterField(
            model_name='fbprojects',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.doc_upload_path),
        ),
    ]
